#!/usr/bin/python3
#Dibuat Oleh Noprian
#BLackWhiteTEam

import math
print (" ___ __     ___ _______    ")
print (" | | \ \    | | |_|  \_\   ")
print (" | |  \ \   | | |_|   \_\  ")
print (" | |   \ \  | | |_|    \_\ ")
print (" | |    \ \_| | |_|    /_/ ")
print ("|___|    \____| |_|___/_/  ")
print ("-------------------------- ")
print ("")
print ("Mencari Kaurtil ")
print ("")
print ("Rumus Kuartil ")
print ("")
print (" Q = L + P (n - Fks )")
print ("              FQ     ")
print ("")
print ("Mencari Quarti 1/4 ")
print ("")
a = input ("Masukan Nilai L : ")
b = input ("Masukan Nilai P : ")
c = input ("Masukan 1/4n    : ")
d = input ("Masukan Fks     : ")
e = input ("Masukan FQ      : ")
a = int and float (a)
b = int and float (b)
c = int and float (c)
d = int and float (d)
e = int and float (e)
print ("Hasil = ", b*(c-d)/e+a )
print ("")
print ("")
print (" ___ __     ___ _______    ")
print (" | | \ \    | | |_|  \_\   ")
print (" | |  \ \   | | |_|   \_\  ")
print (" | |   \ \  | | |_|    \_\ ")
print (" | |    \ \_| | |_|    /_/ ")
print ("|___|    \____| |_|___/_/  ")
print ("-------------------------- ")
print ("")
print ("Mencari Quarti 1/5n ")
print ("")
a = input ("Masukan Nilai L : ")
b = input ("Masukan Nilai P : ")
c = input ("Masukan 1/5n    : ")
d = input ("Masukan Fks     : ")
e = input ("Masukan FQ      : ")
a = int and float (a)
b = int and float (b)
c = int and float (c)
d = int and float (d)
e = int and float (e)
print ("Hasil = ", b*(c-d)/e+a )
print ("")
print ("")
print (" ___ __     ___ _______    ")
print (" | | \ \    | | |_|  \_\   ")
print (" | |  \ \   | | |_|   \_\  ")
print (" | |   \ \  | | |_|    \_\ ")
print (" | |    \ \_| | |_|    /_/ ")
print ("|___|    \____| |_|___/_/  ")
print ("-------------------------- ")
print ("")
print ("Mencari Quarti 3/4 ")
print ("")
a = input ("Masukan Nilai L : ")
b = input ("Masukan Nilai P : ")
c = input ("Masukan 3/4n    : ")
d = input ("Masukan Fks     : ")
e = input ("Masukan FQ      : ")
a = int and float (a)
b = int and float (b)
c = int and float (c)
d = int and float (d)
e = int and float (e)
print ("Hasil = ", b*(c-d)/e+a )
print("")
print (" TerimaKasih ")
print ("                            BLackWhiteTeam")

