#!/usr/bin/python3
#DiBuat OLeh Noprianto
#BLackWhiteTeam
import math
print (" ___ __     ___ _______    ")
print (" | | \ \    | | |_|  \_\   ")
print (" | |  \ \   | | |_|   \_\  ")
print (" | |   \ \  | | |_|    \_\ ")
print (" | |    \ \_| | |_|    /_/ ")
print ("|___|    \____| |_|___/_/  ")
print ("-------------------------- ")
print ("")
print ("")
print (" Penjumlahan 2 Bilangan ") 
print("")
x = input ("Bilangan Pertama: ")
y = input ("Bilangan Kedua  : ")
x = int and float (x)
y = int and float (y) 
print ("Jumlah/Hasil = ", (x+y) )
print ("")
print (" Tekan ctrl+c Untuk Keluar!!!  ")
print ("")
print (" Penjumlahan 3 Bilangan ") 
print("")
x = input ("Bilangan Pertama: ")
y = input ("Bilangan Kedua  : ")
z = input ("Bilangan Ketiga : ")
x = int and float (x)
y = int and float (y) 
z = int and float (z)
print ("Jumlah/Hasil = ", (x+y+z) )
print ("")
print (" Tekan ctrl+c Untuk Keluar!!!  ")
print ("")
print (" Penjumlahan 4 Bilangan ") 
print("")
a = input ("Bilangan Pertama: ")
b = input ("Bilangan Kedua  : ")
c = input ("Bilangan Ketiga : ")
d = input ("Bilangan KeEmpat: ")
a = int and float (a)
b = int and float (b) 
c = int and float (c)
d = int and float (d)
print ("Jumlah/Hasil = ", (a+b+c+d) )
print ("")
print (" Tekan ctrl+c Untuk Keluar!!!  ")
print ("")
print (" Penjumlahan 5 Bilangan ") 
print("")
a = input ("Bilangan Pertama: ")
b = input ("Bilangan Kedua  : ")
c = input ("Bilangan Ketiga : ")
d = input ("Bilangan KeEmpat: ")
e = input ("Bilangan KeLima : ")
a = int and float (a)
b = int and float (b) 
c = int and float (c)
d = int and float (d)
e = int and float (e)
print ("Jumlah/Hasil = ", (a+b+c+d+e) )
print ("")
print (" Tekan ctrl+c Untuk Keluar!!!  ")
print ("")
print (" Penjumlahan 6 Bilangan ") 
print("")
a = input ("Bilangan Pertama: ")
b = input ("Bilangan Kedua  : ")
c = input ("Bilangan Ketiga : ")
d = input ("Bilangan Keempat: ")
e = input ("Bilangan Kelima : ")
f = input ("Bilangan Keenam : ")
a = int and float (a)
b = int and float (b) 
c = int and float (c)
d = int and float (d)
e = int and float (e)
f = int and float (f)
print ("Jumlah/Hasil = ", (a+b+c+d+e+f) )
print ("")
print (" Tekan ctrl+c Untuk Keluar!!!  ")
print ("")
print (" Penjumlahan 7 Bilangan ") 
print("")
a = input ("Bilangan Pertama: ")
b = input ("Bilangan Kedua  : ")
c = input ("Bilangan Ketiga : ")
d = input ("Bilangan Keempat: ")
e = input ("Bilangan Kelima : ")
f = input ("Bilangan Keenam : ")
g = input ("Bilangan Ketujuh: ")
a = int and float (a)
b = int and float (b) 
c = int and float (c)
d = int and float (d)
e = int and float (e)
f = int and float (f)
g = int and float (g)
print ("Jumlah/Hasil = ", (a+b+c+d+e+f+g) )
print ("")
print (" Tekan ctrl+c Untuk Keluar!!!  ")
print ("")
print (" Penjumlahan 8 Bilangan ") 
print("")
a = input ("Bilangan Pertama   : ")
b = input ("Bilangan Kedua     : ")
c = input ("Bilangan Ketiga    : ")
d = input ("Bilangan Keempat   : ")
e = input ("Bilangan Kelima    : ")
f = input ("Bilangan Keenam    : ")
g = input ("Bilangan Ketujuh   : ")
h = input ("Bilangan Kedelapan : ")
a = int and float (a)
b = int and float (b) 
c = int and float (c)
d = int and float (d)
e = int and float (e)
f = int and float (f)
g = int and float (g)
h = int and float (h)
print ("Jumlah/Hasil = ", (a+b+c+d+e+f+g+h) )
print ("")
print (" Tekan ctrl+c Untuk Keluar!!!  ")
print ("")
print (" Penjumlahan 9 Bilangan ") 
print("")
a = input ("Bilangan Pertama   : ")
b = input ("Bilangan Kedua     : ")
c = input ("Bilangan Ketiga    : ")
d = input ("Bilangan Keempat   : ")
e = input ("Bilangan Kelima    : ")
f = input ("Bilangan Keenam    : ")
g = input ("Bilangan Ketujuh   : ")
h = input ("Bilangan Kedelapan : ")
i = input ("Bilangan Kesembilan: ")
a = int and float (a)
b = int and float (b) 
c = int and float (c)
d = int and float (d)
e = int and float (e)
f = int and float (f)
g = int and float (g)
h = int and float (h)
i = int and float (i)
print ("Jumlah/Hasil = ", (a+b+c+d+e+f+g+h+i) )
print ("")
print (" Tekan ctrl+c Untuk Keluar!!!  ")
print ("")
print (" Penjumlahan 10 Bilangan ") 
print("")
a = input ("Bilangan Pertama   : ")
b = input ("Bilangan Kedua     : ")
c = input ("Bilangan Ketiga    : ")
d = input ("Bilangan Keempat   : ")
e = input ("Bilangan Kelima    : ")
f = input ("Bilangan Keenam    : ")
g = input ("Bilangan Ketujuh   : ")
h = input ("Bilangan Kedelapan : ")
i = input ("Bilangan Kesembilan: ")
j = input ("Bilangan Kesepuluh : ")
a = int and float (a)
b = int and float (b) 
c = int and float (c)
d = int and float (d)
e = int and float (e)
f = int and float (f)
g = int and float (g)
h = int and float (h)
i = int and float (i)
j = int and float (j)
print ("Jumlah/Hasil = ", (a+b+c+d+e+f+g+h+i+j) )
print ("")
print (" Tekan ctrl+c Untuk Keluar!!!  ")
print (" TrimaKasih ")
print ("")
print (" Telah Berkunjung ") 











